# -*- coding: utf-8 -*-
"""NiceMorning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com
"""




import random
from random import randint
import time
from pushbullet import Pushbullet
import sys
from datetime import datetime

hello = ['안녕히 주무셨어요?😄\n', '쫀아~~❤️\n', '좋은 아침입니당~!👋👋\n', '활기찬 아침이네요!\n', '👋❤️푹 잘 주무셨나요?\n', ' ']
hello2 = ['✊오늘 하루도 파이팅하세요!✊\n', '조은 하루~~:D\n', '✊😊✊행복하고 힘찬 하루되세요!!\n', '오늘도 무탈하세용🧡\n', '졸린 아침, 시원한 물 한잔 하고 잠을 깨봐요!\n', '즐겁고 행복한 하루보내세요!!!\n']
emoji = ['☆*: .｡. o(≧▽≦)o .｡.:*☆', '(❁´◡`❁)', '╰(*°▽°*)╯', '(●^◡^●)', '=D', '^3^*', '😘💕', '✊✊😊🧡❤️', ' ']
mom = ['엄마!', '엄마,', '']
dad = ['아빠!', '아빠,', '']


access_token = 'your_pushbullet_access_token'

def send():
  pb = Pushbullet(access_token)
  print(pb.devices)

  delay = randint(0, 7199)
  time.sleep(delay)

  device = pb.devices[1]
  now = datetime.now()

  to_mom = random.choice(mom) + ' ' + random.choice(hello) + random.choice(hello2) + random.choice(emoji)
  to_dad = random.choice(dad) + ' ' + random.choice(hello) + random.choice(hello2) + random.choice(emoji)

  push = pb.push_sms(device, "+821000000000", to_mom)
  push1 = pb.push_sms(device, "+821000000000", to_dad)

  f = open("nicemorningresult.txt", 'a', encoding='utf-8')
  f.write('['+str(now)+']'+'\n엄마>>>\t'+to_mom+'\n아빠>>>\t'+to_dad+'\n\n')
  f.close()

send()